name = "car-usage-tracker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "car-tracker-db"
database_id = "YOUR_D1_DATABASE_ID"

[vars]
ADMIN_USER_ID = "U3e8201d1672346cac5fde4a9bc8d728c"
ALLOWED_ORIGIN = "https://fn-car.pages.dev"
